import type { MasterRole, RolePermissions } from '../types'

const allow = (): RolePermissions => ({
  canCreateTask: true,
  canEditTask: true,
  canDeleteTask: true,
  canMoveTask: true,
  canHandoffTask: true,
  canCommentTask: true,
  canCreateDivision: true,
  canEditDivision: true,
  canDeleteDivision: true,
  canManageDivisionTeams: true,
  canEditHandoffRequirements: true,
  canManageUsers: true,
  canInviteUsers: true,
  canDeleteUsers: true,
  canChangeUserRoles: true,
  canManageRoles: true,
  canConfigureWorkflow: true,
  canApproveHandoff: true,
  canCreateProject: true,
  canEditProject: true,
  canDeleteProject: true,
  canAdvanceProjectStage: true,
  canEditProjectWeights: true,
  canCloseProject: true,
  canRequestSegmentChange: true,
  canApproveSegmentChange: true,
})

const none = (): RolePermissions => ({
  canCreateTask: false,
  canEditTask: false,
  canDeleteTask: false,
  canMoveTask: false,
  canHandoffTask: false,
  canCommentTask: false,
  canCreateDivision: false,
  canEditDivision: false,
  canDeleteDivision: false,
  canManageDivisionTeams: false,
  canEditHandoffRequirements: false,
  canManageUsers: false,
  canInviteUsers: false,
  canDeleteUsers: false,
  canChangeUserRoles: false,
  canManageRoles: false,
  canConfigureWorkflow: false,
  canApproveHandoff: false,
  canCreateProject: false,
  canEditProject: false,
  canDeleteProject: false,
  canAdvanceProjectStage: false,
  canEditProjectWeights: false,
  canCloseProject: false,
  canRequestSegmentChange: false,
  canApproveSegmentChange: false,
})

export const SEED_ROLES: MasterRole[] = [
  {
    id: 'super_admin',
    name: 'Super Admin',
    description: 'Akses penuh ke seluruh sistem, divisi, user, role, dan konfigurasi workflow.',
    color: '#E31E24',
    rank: 100,
    isSystem: true,
    scopeRestriction: 'any',
    permissions: allow(),
  },
  {
    id: 'team_admin',
    name: 'Kadiv (Kepala Divisi)',
    description: 'Mengelola tugas dan member di divisi yang dipimpin. Default approver handoff & segment change.',
    color: '#7C3AED',
    rank: 70,
    isSystem: true,
    scopeRestriction: 'own_division',
    permissions: {
      ...none(),
      canCreateTask: true,
      canEditTask: true,
      canDeleteTask: true,
      canMoveTask: true,
      canHandoffTask: true,
      canCommentTask: true,
      canEditDivision: true,
      canEditHandoffRequirements: true,
      canManageUsers: true,
      canInviteUsers: true,
      canChangeUserRoles: true,
      canApproveHandoff: true,
      canCreateProject: true,
      canEditProject: true,
      canAdvanceProjectStage: true,
      canEditProjectWeights: true,
      canRequestSegmentChange: true,
      canApproveSegmentChange: true,
    },
  },
  {
    id: 'team_lead',
    name: 'Kadep (Kepala Departemen / Team)',
    description: 'Memimpin satu team di dalam divisi. Approver opsional di stage Asal/Tujuan. Bisa approve segment change. Penghapusan tugas perlu approval Kadiv.',
    color: '#0891B2',
    rank: 50,
    isSystem: true,
    scopeRestriction: 'own_department',
    permissions: {
      ...none(),
      canCreateTask: true,
      canEditTask: true,
      canMoveTask: true,
      canHandoffTask: true,
      canCommentTask: true,
      canEditHandoffRequirements: true,
      canApproveHandoff: true,
      canRequestSegmentChange: true,
      canApproveSegmentChange: true,
    },
  },
  {
    id: 'member',
    name: 'Member',
    description: 'Anggota team - dapat membuat, mengedit, dan memindah tugas di team-nya.',
    color: '#2563EB',
    rank: 30,
    isSystem: true,
    scopeRestriction: 'own_division',
    permissions: {
      ...none(),
      canCreateTask: true,
      canEditTask: true,
      canMoveTask: true,
      canHandoffTask: true,
      canCommentTask: true,
    },
  },
  {
    id: 'staff',
    name: 'Staff',
    description: 'Staff team - mengerjakan tugas dalam team. Tidak dapat handoff atau mengubah struktur.',
    color: '#059669',
    rank: 20,
    isSystem: true,
    scopeRestriction: 'own_department',
    permissions: {
      ...none(),
      canCreateTask: true,
      canEditTask: true,
      canMoveTask: true,
      canCommentTask: true,
    },
  },
  {
    id: 'viewer',
    name: 'Viewer',
    description: 'Read-only - hanya dapat melihat board dan dashboard.',
    color: '#64748B',
    rank: 10,
    isSystem: true,
    scopeRestriction: 'any',
    permissions: none(),
  },
]
