import type { ActivityLog, Department, HandoffRequirementField, RequirementFieldType, Task, Team } from '../types'
import { nowIso, uid } from '../utils/helpers'
import { defaultKanbanConfig, osmKanbanConfig } from '../utils/kanbanDefaults'

const DEFAULT_DIV_WORKFLOW = {
  approverRoleIds: ['team_admin'],
  requireApproval: true,
  autoFlagOnDone: true,
}

const dept = (teamId: string, name: string, description: string): Department => ({
  id: `dept_${teamId.replace('team_', '')}_${name.toLowerCase().replace(/[^a-z0-9]+/g, '_')}`,
  teamId,
  name,
  description,
  createdAt: nowIso(),
})

const req = (
  slug: string,
  label: string,
  type: RequirementFieldType,
  required: boolean,
  description = '',
  applicableFromTeamIds: string[] = [],
): HandoffRequirementField => ({
  id: `req_${slug}`,
  label,
  description,
  type,
  required,
  applicableFromTeamIds,
})

export const SEED_TEAMS: Team[] = [
  {
    id: 'team_itd',
    name: 'IT Development',
    color: '#5b6af8',
    acronym: 'ITD',
    description: 'Tim pengembangan aplikasi internal & integrasi sistem.',
    memberCount: 8,
    createdAt: nowIso(),
    kanbanConfig: defaultKanbanConfig(),
    divisionWorkflow: DEFAULT_DIV_WORKFLOW,
    departments: [
      dept('team_itd', 'Frontend', 'UI/UX & web app development.'),
      dept('team_itd', 'Backend', 'API, services, dan database engineering.'),
      dept('team_itd', 'DevOps', 'CI/CD, deployment, dan infrastruktur kode.'),
    ],
    handoffRequirements: [
      req('itd_brd', 'Dokumen Spesifikasi (BRD/SRS)', 'document', true, 'Wajib: file PDF/DOCX yang berisi kebutuhan fungsional & non-fungsional.'),
      req('itd_acceptance', 'Kriteria Acceptance', 'longtext', true, 'List checklist apa yang dianggap "selesai" oleh pemberi tugas.'),
      req('itd_target_date', 'Target Go-Live', 'date', true),
      req('itd_design', 'Mockup / Design Reference', 'url', false, 'Link Figma / Penpot kalau ada.'),
      req('itd_from_qat', 'Bug Defect Report', 'document', true, 'Hanya untuk handoff dari QAT — wajib report defect dari hasil testing.', ['team_qat']),
    ],
  },
  {
    id: 'team_net',
    name: 'Network & Infra',
    color: '#8b5cf6',
    acronym: 'NET',
    description: 'Tim infrastruktur jaringan, server, dan keamanan perimeter.',
    memberCount: 5,
    createdAt: nowIso(),
    kanbanConfig: osmKanbanConfig(),
    divisionWorkflow: DEFAULT_DIV_WORKFLOW,
    departments: [
      dept('team_net', 'Server Admin', 'OS, virtualisasi, dan datacenter.'),
      dept('team_net', 'Network Engineering', 'Routing, switching, dan WAN.'),
      dept('team_net', 'Security', 'Firewall, IDS/IPS, dan kepatuhan.'),
    ],
    handoffRequirements: [
      req('net_arch', 'Diagram Arsitektur Jaringan', 'document', true, 'Topologi jaringan target (PDF/PNG/Visio).'),
      req('net_risk', 'Risk Assessment & Mitigasi', 'document', true),
      req('net_window', 'Jadwal Window Pemeliharaan', 'date', true),
      req('net_change_approval', 'Change Request sudah disetujui CAB', 'checkbox', true),
      req('net_rollback', 'Rollback Plan', 'longtext', false),
    ],
  },
  {
    id: 'team_biz',
    name: 'Business Analyst',
    color: '#06b6d4',
    acronym: 'BIZ',
    description: 'Tim analis kebutuhan bisnis & dokumentasi proses.',
    memberCount: 6,
    createdAt: nowIso(),
    kanbanConfig: defaultKanbanConfig(),
    divisionWorkflow: DEFAULT_DIV_WORKFLOW,
    departments: [
      dept('team_biz', 'Process Analysis', 'Pemetaan proses dan BPMN.'),
      dept('team_biz', 'Documentation', 'BRD, SRS, dan dokumentasi standar.'),
      dept('team_biz', 'Stakeholder Mgmt', 'Liaison dengan bisnis & klien.'),
    ],
    handoffRequirements: [
      req('biz_stakeholder', 'Daftar Stakeholder Terlibat', 'longtext', true),
      req('biz_current_doc', 'Dokumen Proses Bisnis Saat Ini (AS-IS)', 'document', false),
      req('biz_target', 'Tujuan / Outcome yang Diharapkan', 'longtext', true),
    ],
  },
  {
    id: 'team_qat',
    name: 'QA & Testing',
    color: '#10b981',
    acronym: 'QAT',
    description: 'Tim quality assurance, regression, dan automated testing.',
    memberCount: 4,
    createdAt: nowIso(),
    kanbanConfig: defaultKanbanConfig(),
    divisionWorkflow: DEFAULT_DIV_WORKFLOW,
    departments: [
      dept('team_qat', 'Manual Testing', 'Eksplorasi & functional testing.'),
      dept('team_qat', 'Automation', 'Otomasi UI & API testing.'),
      dept('team_qat', 'Performance', 'Load, stress, dan benchmark.'),
    ],
    handoffRequirements: [
      req('qat_test_plan', 'Test Plan & Test Cases', 'document', true),
      req('qat_env_ready', 'Lingkungan Testing Siap', 'checkbox', true, 'Konfirmasi staging/UAT sudah deploy versi terbaru.'),
      req('qat_build_url', 'Link Build / APK / URL Deploy', 'url', true),
      req('qat_known_issues', 'Known Issues / Bug Defer List', 'longtext', false),
      req('qat_from_itd', 'API Documentation', 'url', true, 'Hanya untuk handoff dari ITD — link Swagger/Postman.', ['team_itd']),
      req('qat_from_net', 'Network Topology Doc', 'document', true, 'Hanya untuk handoff dari NET — diagram jaringan yang akan diuji.', ['team_net']),
    ],
  },
]

const dPlus = (days: number) => {
  const d = new Date()
  d.setDate(d.getDate() + days)
  return d.toISOString()
}

const dMinus = (days: number) => {
  const d = new Date()
  d.setDate(d.getDate() - days)
  return d.toISOString()
}

const baseTask = (overrides: Partial<Task>): Task => ({
  id: uid('tsk'),
  title: '',
  description: '',
  priority: 'medium',
  status: 'backlog',
  teamId: 'team_itd',
  assignees: [],
  tags: [],
  deadline: null,
  createdAt: dMinus(Math.floor(Math.random() * 14) + 1),
  updatedAt: nowIso(),
  storyPoints: 3,
  completedAt: null,
  handoffHistory: [],
  attachmentCount: 0,
  commentCount: 0,
  parentTaskId: null,
  subTasks: [],
  comments: [],
  departmentId: null,
  projectId: 'prj_internal_pgncom',
  stage: 'build_to_operate',
  ...overrides,
})

export const SEED_TASKS: Task[] = [
  baseTask({
    title: 'Survey lapangan instalasi Radio Trunking Site 1',
    description: 'Lakukan survey lokasi untuk instalasi base station radio trunking di wellpad PHE.',
    priority: 'high',
    status: 'in_progress',
    teamId: 'team_net',
    departmentId: 'dept_net_network_engineering',
    assignees: ['Bayu', 'Citra'],
    tags: ['phe', 'radio-trunking', 'survey'],
    deadline: dPlus(7),
    storyPoints: 8,
    projectId: 'prj_radio_trunking_phe',
    stage: 'build_to_operate',
  }),
  baseTask({
    title: 'Instalasi & komisioning Base Station PHE',
    description: 'Pasang & komisioning 3 base station radio trunking.',
    priority: 'high',
    status: 'backlog',
    teamId: 'team_net',
    assignees: ['Bayu'],
    tags: ['phe', 'instalasi'],
    deadline: dPlus(21),
    storyPoints: 13,
    projectId: 'prj_radio_trunking_phe',
    stage: 'build_to_operate',
  }),
  baseTask({
    title: 'Maintenance bulanan radio trunking PHE',
    description: 'SLA care: cek RSSI, baterai backup, antenna alignment.',
    priority: 'medium',
    status: 'backlog',
    teamId: 'team_net',
    assignees: ['Citra'],
    tags: ['phe', 'maintenance'],
    deadline: dPlus(30),
    storyPoints: 5,
    projectId: 'prj_radio_trunking_phe',
    stage: 'operate_to_assure',
  }),
  baseTask({
    title: 'Migrasi Database ke PostgreSQL 16',
    description: 'Migrasi seluruh service core ke PostgreSQL 16 dengan minimal downtime. Termasuk update driver dan smoke test.',
    priority: 'critical',
    status: 'in_progress',
    teamId: 'team_itd',
    departmentId: 'dept_itd_backend',
    assignees: ['Aditya', 'Rina'],
    tags: ['database', 'migration', 'urgent'],
    deadline: dPlus(3),
    storyPoints: 13,
    attachmentCount: 4,
    commentCount: 6,
    subTasks: [
      { id: uid('st'), title: 'Audit query lambat', done: true },
      { id: uid('st'), title: 'Update connection pool', done: true },
      { id: uid('st'), title: 'Dry-run di staging', done: false },
      { id: uid('st'), title: 'Rollback playbook', done: false },
    ],
  }),
  baseTask({
    title: 'Setup VPN Baru untuk Remote Access',
    departmentId: 'dept_net_security',
    description: 'Konfigurasi WireGuard untuk akses internal dari perangkat karyawan remote.',
    priority: 'high',
    status: 'backlog',
    teamId: 'team_net',
    assignees: ['Bayu'],
    tags: ['vpn', 'security'],
    deadline: dPlus(10),
    storyPoints: 5,
    commentCount: 2,
  }),
  baseTask({
    title: 'Analisis Kebutuhan Sistem Billing',
    description: 'Wawancara stakeholder finance, susun BRD modul billing baru.',
    priority: 'medium',
    status: 'review',
    teamId: 'team_biz',
    assignees: ['Sari', 'Dina'],
    tags: ['analysis', 'billing'],
    deadline: dPlus(5),
    storyPoints: 8,
    attachmentCount: 2,
    commentCount: 4,
  }),
  baseTask({
    title: 'Pengujian Regresi Modul Pembayaran',
    description: 'Eksekusi suite regresi pembayaran end-to-end termasuk gateway pihak ketiga.',
    priority: 'high',
    status: 'backlog',
    teamId: 'team_qat',
    assignees: ['Putra', 'Lina'],
    tags: ['regression', 'payment'],
    deadline: dPlus(7),
    storyPoints: 5,
  }),
  baseTask({
    title: 'Implementasi SSO dengan Active Directory',
    departmentId: 'dept_itd_backend',
    description: 'Single sign-on untuk seluruh aplikasi internal terhubung ke AD korporat.',
    priority: 'high',
    status: 'in_progress',
    teamId: 'team_itd',
    assignees: ['Aditya', 'Hendra'],
    tags: ['auth', 'sso'],
    deadline: dPlus(14),
    storyPoints: 8,
    attachmentCount: 1,
  }),
  baseTask({
    title: 'Upgrade Firewall Perimeter',
    departmentId: 'dept_net_security',
    description: 'Upgrade firmware FortiGate dan revisi rule sesuai compliance terbaru.',
    priority: 'critical',
    status: 'review',
    teamId: 'team_net',
    assignees: ['Bayu', 'Citra'],
    tags: ['firewall', 'compliance'],
    deadline: dPlus(2),
    storyPoints: 8,
    attachmentCount: 3,
    commentCount: 5,
    handoffHistory: [
      {
        id: uid('hof'),
        fromTeamId: 'team_itd',
        toTeamId: 'team_net',
        reason: 'Eksekusi konfigurasi memerlukan tim infrastruktur.',
        timestamp: dMinus(2),
        by: 'Aditya',
      },
    ],
  }),
  baseTask({
    title: 'Dokumentasi SLA untuk Klien Enterprise',
    description: 'Susun SLA komprehensif untuk klien tier-1 dan review legal.',
    priority: 'low',
    status: 'done',
    teamId: 'team_biz',
    assignees: ['Sari'],
    tags: ['documentation', 'sla'],
    deadline: dMinus(2),
    storyPoints: 3,
    completedAt: dMinus(1),
  }),
  baseTask({
    title: 'Load Testing API Gateway',
    description: 'Stress test API gateway untuk memvalidasi target 5.000 RPS.',
    priority: 'high',
    status: 'in_progress',
    teamId: 'team_qat',
    assignees: ['Putra'],
    tags: ['performance', 'api'],
    deadline: dPlus(6),
    storyPoints: 5,
    commentCount: 3,
  }),
  baseTask({
    title: 'Refactor Microservice Auth',
    departmentId: 'dept_itd_backend',
    description: 'Pisahkan tanggung jawab token issuance dan session storage.',
    priority: 'medium',
    status: 'backlog',
    teamId: 'team_itd',
    assignees: ['Hendra'],
    tags: ['refactor', 'auth'],
    deadline: dPlus(20),
    storyPoints: 8,
  }),
  baseTask({
    title: 'Monitoring Dashboard Jaringan',
    description: 'Dashboard Grafana terpusat untuk metrik core router & switch.',
    priority: 'medium',
    status: 'done',
    teamId: 'team_net',
    assignees: ['Citra'],
    tags: ['monitoring', 'grafana'],
    deadline: dMinus(4),
    storyPoints: 5,
    completedAt: dMinus(3),
  }),
  baseTask({
    title: 'Pemetaan Proses Bisnis CRM Baru',
    description: 'Susun BPMN proses penjualan, after-sales, dan customer support pada CRM baru.',
    priority: 'high',
    status: 'backlog',
    teamId: 'team_biz',
    assignees: ['Dina', 'Maya'],
    tags: ['bpmn', 'crm'],
    deadline: dPlus(12),
    storyPoints: 8,
    attachmentCount: 2,
  }),
  baseTask({
    title: 'Regression Suite Automation',
    departmentId: 'dept_qat_automation',
    description: 'Otomasi suite regresi UI menggunakan Playwright + CI integration.',
    priority: 'medium',
    status: 'in_progress',
    teamId: 'team_qat',
    assignees: ['Lina'],
    tags: ['automation', 'playwright'],
    deadline: dPlus(15),
    storyPoints: 8,
    commentCount: 1,
    handoffHistory: [
      {
        id: uid('hof'),
        fromTeamId: 'team_itd',
        toTeamId: 'team_qat',
        reason: 'Implementasi otomasi pengujian lebih cocok dipimpin oleh QA.',
        timestamp: dMinus(5),
        by: 'Aditya',
      },
    ],
  }),
  baseTask({
    title: 'Operasional Sistem Monitoring SCADA',
    departmentId: 'dept_net_server_admin',
    description: 'Operasi & pemeliharaan berkelanjutan platform SCADA: monitoring uptime, patching keamanan rutin, eskalasi insiden.',
    priority: 'medium',
    status: 'operate',
    teamId: 'team_net',
    assignees: ['Citra', 'Bayu'],
    tags: ['operations', 'scada', 'maintenance'],
    deadline: null,
    storyPoints: 5,
    commentCount: 2,
  }),
]

export const SEED_LOGS: ActivityLog[] = [
  {
    id: uid('log'),
    type: 'team_added',
    message: 'Tim IT Development ditambahkan',
    taskId: null,
    taskTitle: null,
    fromTeamId: null,
    toTeamId: 'team_itd',
    timestamp: dMinus(20),
  },
  {
    id: uid('log'),
    type: 'team_added',
    message: 'Tim Network & Infra ditambahkan',
    taskId: null,
    taskTitle: null,
    fromTeamId: null,
    toTeamId: 'team_net',
    timestamp: dMinus(20),
  },
  {
    id: uid('log'),
    type: 'task_created',
    message: 'Tugas "Migrasi Database ke PostgreSQL 16" dibuat',
    taskId: SEED_TASKS[0].id,
    taskTitle: SEED_TASKS[0].title,
    fromTeamId: null,
    toTeamId: 'team_itd',
    timestamp: dMinus(7),
  },
  {
    id: uid('log'),
    type: 'task_moved',
    message: 'Tugas "Migrasi Database ke PostgreSQL 16" dipindah ke Dikerjakan',
    taskId: SEED_TASKS[0].id,
    taskTitle: SEED_TASKS[0].title,
    fromTeamId: null,
    toTeamId: 'team_itd',
    timestamp: dMinus(5),
  },
  {
    id: uid('log'),
    type: 'handoff',
    message: 'Tugas "Upgrade Firewall Perimeter" diserahkan ke Network & Infra',
    taskId: SEED_TASKS[5].id,
    taskTitle: SEED_TASKS[5].title,
    fromTeamId: 'team_itd',
    toTeamId: 'team_net',
    timestamp: dMinus(2),
  },
  {
    id: uid('log'),
    type: 'task_done',
    message: 'Tugas "Dokumentasi SLA untuk Klien Enterprise" diselesaikan',
    taskId: SEED_TASKS[6].id,
    taskTitle: SEED_TASKS[6].title,
    fromTeamId: 'team_biz',
    toTeamId: null,
    timestamp: dMinus(1),
  },
  {
    id: uid('log'),
    type: 'task_edited',
    message: 'Tugas "Implementasi SSO dengan Active Directory" diperbarui',
    taskId: SEED_TASKS[4].id,
    taskTitle: SEED_TASKS[4].title,
    fromTeamId: null,
    toTeamId: 'team_itd',
    timestamp: dMinus(1),
  },
  {
    id: uid('log'),
    type: 'task_done',
    message: 'Tugas "Monitoring Dashboard Jaringan" diselesaikan',
    taskId: SEED_TASKS[9].id,
    taskTitle: SEED_TASKS[9].title,
    fromTeamId: 'team_net',
    toTeamId: null,
    timestamp: dMinus(3),
  },
  {
    id: uid('log'),
    type: 'task_created',
    message: 'Tugas "Load Testing API Gateway" dibuat',
    taskId: SEED_TASKS[7].id,
    taskTitle: SEED_TASKS[7].title,
    fromTeamId: null,
    toTeamId: 'team_qat',
    timestamp: dMinus(3),
  },
  {
    id: uid('log'),
    type: 'handoff',
    message: 'Tugas "Regression Suite Automation" diserahkan ke QA & Testing',
    taskId: SEED_TASKS[11].id,
    taskTitle: SEED_TASKS[11].title,
    fromTeamId: 'team_itd',
    toTeamId: 'team_qat',
    timestamp: dMinus(5),
  },
]
